REFACTOR: update version to 'build 2.0.89 built on 04/05/2025'

diff --git a/bin/icarus b/bin/icarus
--- a/bin/icarus
+++ b/bin/icarus
@@ -99,7 +99,7 @@ if [[ "$1" == '--update' ]]; then
         git reset --hard origin/HEAD
         git pull
         make build
-    } >"${log_filepath}" 2>&1
+    } >"${log_filepath}" 2>&1 || echo -e "${bg_red}${black}[WARNING]${end} - Failed to install icarus CLI" && exit 1
     echo -e "icarus CLI updated!"
     echo -e ""
 fi
@@ -112,7 +112,7 @@ if [ ! -x "${python_interpreter_abs}" ]; then
         pushd "${project_root_dir_abs}"
         rm -rf "${project_root_dir_abs}/build_venv"
         make build
-    } >"${log_filepath}" 2>&1
+    } >"${log_filepath}" 2>&1 || echo -e "${bg_red}${black}[WARNING]${end} - Failed to install icarus CLI" && exit 1
     echo -e "icarus CLI installed!"
     echo -e ""
 fi
