REFACTOR: carlogtt updates

diff --git a/bin/icarus b/bin/icarus
--- a/bin/icarus
+++ b/bin/icarus
@@ -78,7 +78,7 @@ declare -r script_dir_abs
 # Temporarily disable 'errexit' to allow for retries
 set +e
 # Sourcing existing bashrc to export current PATH
-source "${HOME}/.bashrc" || echo -e "${red}[ERROR] [$(date '+%Y-%m-%d %T %Z')] Failed to source .bashrc${end}"
+source "${HOME}/.bashrc" || echo -e "${red}[$(date '+%Y-%m-%d %T %Z')] [ERROR] Failed to source .bashrc${end}"
 # Re-enable 'errexit'
 set -e
 
@@ -95,8 +95,8 @@ run_as_sudo() {
     sudo -v
 }
 
-log_time() {
-    echo -e "[$(date '+%Y-%m-%d %T %Z')]"
+log_message() {
+    echo -e "[$(date '+%Y-%m-%d %T %Z')] ${1}"
 }
 
 ########################################################################
